### ISSUE TITLE
Can we connect ChatGPT to sefaria database?

### ISSUE THREAD

**Issue by gamcoh** [Sefaria/LLM#4]
Hi guys,

Did someone already tried to connect an efficient LLM to the sefaria database?

Personally I would need something like that to search for references, for instance :

- "Where did R. Saadia Gaon talked about free will"
- "He talked about it in his work Emunot VeDeot 4:2" (with a link to the actual text)

**Comment by nsantacruz** [comment]
Thank you for this suggestion. This is an ongoing project internally at Sefaria. Users are welcome to download our database and implement this on their own as well. See https://github.com/Sefaria/Sefaria-Project for details on how to set up the database locally. Closing this for now.
